name: base
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - archspec=0.2.5
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - conda=25.3.0
  - conda-libmamba-solver=25.3.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cpp-expected=1.1.0
  - distro=1.9.0
  - fmt=11.1.4
  - frozendict=2.4.6
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libarchive=3.7.7
  - libcurl=8.13.0
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libiconv=1.18
  - liblzma=5.8.1
  - libmamba=2.0.8
  - libmambapy=2.0.8
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libsolv=0.7.30
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.7
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - mamba=2.0.8
  - menuinst=2.2.0
  - ncurses=6.5
  - nlohmann_json=3.11.3
  - openssl=3.4.1
  - packaging=24.2
  - pip=25.0.1
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.12.9
  - python_abi=3.12
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.8
  - setuptools=78.1.0
  - simdjson=3.12.3
  - spdlog=1.15.2
  - tk=8.6.13
  - tqdm=4.67.1
  - truststore=0.10.1
  - urllib3=2.3.0
  - wheel=0.45.1
  - yaml-cpp=0.8.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - antlr4-python3-runtime==4.13.2
      - anyio==4.11.0
      - apache-tvm-ffi==0.1.2
      - astor==0.8.1
      - attrs==25.4.0
      - bitsandbytes==0.48.2
      - blake3==1.0.8
      - cachetools==6.2.2
      - cbor2==5.7.1
      - click==8.3.1
      - cloudpickle==3.1.2
      - compressed-tensors==0.12.2
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.3.2
      - cuda-python==13.0.3
      - cupy-cuda12x==13.6.0
      - datasets==4.4.1
      - deepspeed==0.18.2
      - depyf==0.20.0
      - dill==0.4.0
      - diskcache==5.6.3
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - email-validator==2.3.0
      - fastapi==0.121.3
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.4.0
      - fastar==0.6.0
      - fastrlock==0.8.3
      - filelock==3.20.0
      - flash-attn==2.8.1
      - flashinfer-python==0.5.2
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - inquirerpy==0.3.4
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.12.0
      - jmespath==1.0.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - langdetect==1.0.9
      - lark==1.2.2
      - latex2sympy2-extended==1.0.6
      - liger-kernel==0.6.3
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - math-verify==0.5.2
      - mdurl==0.1.2
      - mistral-common==1.8.5
      - model-hosting-container-standards==0.1.9
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.19.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.5
      - ninja==1.13.0
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.16.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.2.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.8.1
      - openai-harmony==0.0.8
      - opencv-python-headless==4.12.0.88
      - outlines-core==0.2.11
      - pandas==2.3.3
      - partial-json-parser==0.2.1.1.post7
      - pfzy==0.3.4
      - pillow==12.0.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pybase64==1.4.2
      - pycountry==24.6.1
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - ray==2.51.1
      - referencing==0.37.0
      - regex==2025.11.3
      - rich==14.2.0
      - rich-toolkit==0.16.0
      - rignore==0.7.6
      - rpds-py==0.29.0
      - safetensors==0.7.0
      - scipy==1.16.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.45.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.50.0
      - supervisor==4.3.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - transformers==4.57.1
      - triton==3.5.0
      - trl==0.26.0.dev0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - vllm==0.11.1
      - wandb==0.23.0
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - websockets==15.0.1
      - xformers==0.0.33.post1
      - xgrammar==0.1.25
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /root/miniforge3
